export const LOADING = "[ACCOUNT] LOADING";
export const ACCOUNT_ERROR = "[ACCOUNT] ACCOUNT_ERROR";
export const CHECK_VERIFICATION = "[ACCOUNT] CHECK_VERIFICATION";
export const RESET_VERIFICATION_RECORD = "[ACCOUNT] RESET_CHECK_USER_RECORD";
export const UPDATE_PASSWORD_VALIDATION_ERROR =
  "[ACCOUNT] UPDATE_PASSWORD_VALIDATION_ERROR";
