export const FETCH_CHALLENGE = "[CHALLENGE] FETCH_CHALLENGE_START";
export const FETCH_CHALLENGE_SUCCESS = "[CHALLENGE] FETCH_CHALLENGE_SUCCESS";

export const ENROLLED_CHALLENGE = "[CHALLENGE] ENROLLED_CHALLENGE";
export const ENROLLED_CHALLENGE_SUCCESS =
  "[CHALLENGE] ENROLLED_CHALLENGE_SUCCESS";

export const SELECT_CHALLENGE = "[CHALLENGE] SELECT_CHALLENGE";
export const UPDATE_RECORD = "[CHALLENGE] UPDATE_RECORD";
export const DELETE_CHALLENGE = "[CHALLENGE] DELETE_CHALLENGE";
export const CHALLENGE_ERROR = "[CHALLENGE] CHALLENGE_ERROR";
