export const FETCH_MONTHLY = "[MONTHLY] FETCH_MONTHLY_START ";
export const FETCH_MONTHLY_SUCCESS = "[MONTHLY] FETCH_MONTHLY_SUCCESS";
export const MONTHLY_ERROR = "[MONTHLY] MONTHLY ERROR ";

export const SELECT_MONTHLY = "[MONTHLY] SELECT_MONTHLY";
export const SAVE_MONTHLY = "[MONTHLY] SAVE_MONTHLY";
export const CREATE_MONTHLY = "[MONTHLY] CREATE_MONTHLY_SUCCESS";
export const UPDATE_MONTHLY = "[MONTHLY] UPDATE_MONTHLY";
export const DELETE_MONTHLY = "[MONTHLY] DELETE_MONTHLY";
export const CHANGE_MONTHLY = "[MONTHLY] CHANGE_MONTHLY_MONTH_YEAR";
export const GET_DETAILED = "[MONTHLY] GET_DETAILED";
