export const SEND_DATA = "[SIGN_UP] SEND_DATA_TO_SERVER";
export const SEND_DATA_SUCCESS = "[SIGN_UP] SEND_DATA_SUCCESS";
export const SIGNUP_ERROR = "[SIGN_UP] SIGNUP_ERROR";
export const VALIDATION_ERROR = "[SIGN_UP] VALIDATION_ERROR";
export const CANCEL_SIGNUP = "[SIGN_UP] CANCEL";
