/* TASKS ACTION TYPES*/
export const FETCH_TASKS = "[TASKS] FETCH_TASKS_START";
export const FETCH_TASKS_SUCCESS = "[TASKS] FETCH_TASKS_SUCCESS";

export const ADD_TASKS = "[TASKS] ADD_TASKS_SUCCESS";
export const TASKS_ERROR = "[TASKS] TASKS_ERROR";
export const DELETE_TASKS = "[TASKS] DELETE_TASKS";
export const CHANGE_STATUS = "[TASKS] CHANGE_STATUS";
