/* TASKS ACTION TYPES*/
export const FETCH_START = "[TASKS] FETCHING_DATA_START";
export const FETCH_SUCCESS = "[TASKS] FETCHING_DATA_SUCCESS";

export const ADD_TASKS = "[TASKS] ADD_TASKS_SUCCESS";
export const TASKS_ERROR = "[TASKS] TASKS_ERROR";
export const DELETE_TASKS = "[TASKS] DELETE_TASKS";
export const CHANGE_STATUS = "[TASKS] CHANGE_STATUS to FINISHED or PENDING";

/* SIGN UP ACTION TYPES*/
export const SEND_DATA = "[SIGN_UP] SEND_DATA_TO_SERVER";
export const SEND_DATA_SUCCESS = "[SIGN_UP] SEND_DATA_SUCCESS";
export const SIGNUP_ERROR = "[SIGN_UP] SIGNUP_ERROR";
export const VALIDATION_ERROR = "[SIGN_UP] VALIDATION_ERROR";
export const CANCEL_SIGNUP = "[SIGN_UP] CANCEL";

/* AUTH ACTIONS TYPES*/
export const TRY_LOGIN = "[AUTH] TRY_LOGIN";
export const AUTH_ERROR = "[AUTH] AUTH_ERROR";
export const LOGIN_SUCCESS = "[AUTH] LOGIN_SUCCESS";
export const LOG_OUT = "[AUTH] LOG_OUT";
export const RESET_AUTH = "[AUTH] RESET_AUTH";

/* MONTHLY ACTION TYPES*/
export const FETCH_MONTHLY_START = "[MONTHLY] FETCH_MONTHLY_START ";
export const FETCH_MONTHLY_SUCCESS = "[MONTHLY] FETCH_MONTHLY_SUCCESS";
export const MONTHLY_ERROR = "[MONTHLY] MONTHLY ERROR ";

export const SELECT_MONTHLY = "[MONTHLY] SELECT_MONTHLY";
export const SAVE_MONTHLY = "[MONTHLY] SAVE_MONTHLY";
export const CREATE_MONTHLY = "[MONTHLY] CREATE_MONTHLY_SUCCESS";
export const UPDATE_MONTHLY = "[MONTHLY] UPDATE_MONTHLY";
export const DELETE_MONTHLY = "[MONTHLY] DELETE_MONTHLY";
export const CHANGE_MONTHLY = "[MONTHLY] CHANGE_MONTHLY_MONTH_YEAR";
export const GET_DETAILED = "[MONTHLY] GET_DETAILED";

/* ACCOUNT ACITON TYPES*/
export const LOADING = "[ACCOUNT] LOADING";
export const ACCOUNT_ERROR = "[ACCOUNT] ACCOUNT_ERROR";
export const CHECK_VERIFICATION = "[ACCOUNT] CHECK_VERIFICATION";
export const RESET_VERIFICATION_RECORD = "[ACCOUNT] RESET_CHECK_USER_RECORD";
export const UPDATE_PASSWORD_VALIDATION_ERROR =
  "[ACCOUNT] UPDATE_PASSWORD_VALIDATION_ERROR";

/* CHALLENGE ACTION TYPES */
export const FETCH_CHALLENGE = "[CHALLENGE] FETCH_CHALLENGE_START";
export const FETCH_CHALLENGE_SUCCESS = "[CHALLENGE] FETCH_CHALLENGE_SUCCESS";
export const FETCH_CHALLENGE_FAIELD = "[CHALLENGE] FETCH_CHALLENGE_FAILED";

export const ENROLLED_CHALLENGE = "[CHALLENGE] ENROLLED_CHALLENGE";
export const ENROLLED_CHALLENGE_SUCCESS =
  "[CHALLENGE] ENROLLED_CHALLENGE_SUCCESS";

export const SELECT_CHALLENGE = "[CHALLENGE] SELECT_CHALLENGE";
export const UPDATE_RECORD = "[CHALLENGE] UPDATE_RECORD";
export const DELETE_CHALLENGE = "[CHALLENGE] DELETE_CHALLENGE";
export const CHALLENGE_ERROR = "[CHALLENGE] CHALLENGE_ERROR";
