/* TASKS ACTIONS TYPES*/
export const FETCH_START = "[TASKS] FETCHING_DATA_START";
export const FETCH_SUCCESS = "[TASKS] FETCHING_DATA_SUCCESS";
export const FETCH_FAILED = "[TASKS] FETCHING_DATA_FAILED";

export const ADD_TASKS_SUCCESS = "[TASKS] ADD_TASKS_SUCCESS";
export const ADD_TASKS_FAILED = "[TASKS] ADD_TASKS_FAILED";
export const DELETE_TASKS = "[TASKS] DELETE_TASKS";
export const CHANGE_STATUS = "[TASKS] CHANGE_STATUS to FINISHED or PENDING";

/* SIGN UP ACTIONS TYPES*/
export const SET_USER_NAME = "[SIGN_UP] SET_USER_NAME";
export const SET_USER_ID = "[SIGN_UP] SET_USER_ID";
export const SET_USER_PASSWORD = "[SIGN_UP] ET_USER_PASSWORD";
export const SET_USER_CONFIRMPW = "[SIGN_UP] SET_USER_CONFIRM_PASSWORD";
export const SET_USER_EMAIL = "[SIGN_UP] SET_USER_EMAIL";

export const SEND_DATA = "[SIGN_UP] SEND_DATA_TO_SERVER";
export const SEND_DATA_SUCCESS = "[SIGN_UP] SEND_DATA_SUCCESS  ";
export const SEND_DATA_FAILED = "[SIGN_UP] SEND_DATA_FAILED ";

/* LOG IN ACTIONS TYPES*/

export const TRY_LOGIN = "[AUTH] TRY_LOGIN";
export const LOGIN_FAILED = "[AUTH] LOGIN_FAILED";
export const LOGIN_SUCCESS = "[AUTH] LOGIN_SUCCESS";

/* LOG OUT ACTIONS TYPES*/
export const LOG_OUT = "[AUTH] LOG_OUT";
export const LOG_OUT_FAILED = "[AUTH] LOG_OUT_FAILED";
